### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by TobiasJu** [dimitri/cl-ixf#1]
Hey there,

currently i try to extract the table from an old binary .db2 ixf file, and your library seems to be the only one who can do the trick.
I am new to lisp, so it would be super handy if you could update your README.md and add a "how to" section.

Currently i use Emacs Portacle, but i can't load your ixf.asd file.
best regards!

**Comment by dimitri** [comment]
Hi @TobiasJu ; maybe the easiest way around is to use pgloader (https://github.com/dimitri/pgloader) with the IXF file as input, see an example at https://github.com/dimitri/pgloader/blob/master/test/ixf.load.

**Comment by TobiasJu** [comment]
Thanks, i will have a look!
